version: "3"
services:
  app:
    container_name: "tensorflow_anomary_detection"
    build:
      context: .
      dockerfile: ./Dockerfile
    image: tensorflow_anomary_detection
    deploy:
      resources:
        reservations:
          devices:
            - "driver": "nvidia"
              "capabilities": ["gpu"]
    volumes: 
        - ~/Workspace/anogan_docker/share:/home/DeepLearning
    tty: true
